"""empty message

Revision ID: 34c69809dc71
Revises: 
Create Date: 2023-09-08 18:34:10.566746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c69809dc71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('cost', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('modality', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.String(length=200), nullable=False),
    sa.Column('finish_date', sa.String(length=200), nullable=False),
    sa.Column('contents', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('contents'),
    sa.UniqueConstraint('cost'),
    sa.UniqueConstraint('course'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('finish_date'),
    sa.UniqueConstraint('modality'),
    sa.UniqueConstraint('provider'),
    sa.UniqueConstraint('start_date')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('course')
    op.drop_table('admin')
    # ### end Alembic commands ###
